version: '3'
services:
  postgresql:
    image: postgres:latest
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 5433:5432
    environment:
      - POSTGRES_DB=jibber_jabber_posts
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
volumes:
  postgres-data:
    external: false