version: '3'

services:
  api:
    container_name: "jibber-jabber-posts"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8080
    env_file:
      - posts.env
  db:
    container_name: jibber_jabber_posts_db
    image: postgres:12
    ports:
      - 5432:5432
    env_file:
      - database.env
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
    external: true