version: '3'

services:
  jibber-jabber-posts:
    container_name: "jibber-jabber-posts"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8082:8080
    env_file:
      - posts.env
  jibber_jabber_posts_db:
    container_name: jibber_jabber_posts_db
    image: postgres:12
    ports:
      - 5432:5432
    env_file:
      - database.env
    volumes:
      - jjposts:/var/lib/postgresql/data
volumes:
  jjposts:
    external: true